name: Build node.js project
on: push
jobs:
  job1:
      runs-on: ubuntu-latest
      name: SBOM generator
      outputs:
          output1: ${{ steps.step3.outputs.test }}
      steps:
        - id: step1
        - uses: actions/checkout@v3
        - id: step2
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: '14'
        - run: npm install
        - id: step3
        - name: Create SBOM with CycloneDX 
          uses: CycloneDX/gh-node-module-generatebom@master
            with
              output:'test.app.bom.json' 
      
       
  job2:  
     runs-on: ubuntu-latest
     name: Call api
     needs: job1
     steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install 
      - name: REST API with curl
        run: |
          curl \
          -X POST \
          https://dummyjson.com/products/add \
          -d {"client_payload":{title:"pencil"}}
      - name: PRINT job1 SBOM
        run: echo ${{needs.job1.outputs.output}}
          

  
