name: Build node.js project
on: push
jobs:
 
  job2:  
        runs-on: ubuntu-latest
        name: Install javascript
        steps:
          - uses: actions/checkout@v3
          - name: Setup node
            uses: actions/setup-node@v3
            with:
              node-version: '14'
          - run: npm install
          - name: REST API with curl
          - run: |
              curl \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://dummyjson.com/products/add \
                -d '{"title":"pencil"}'

          

  
