name: Build node.js project
on: push
jobs:
  job1:
      runs-on: ubuntu-latest
      name: SBOM generator
      steps:
        - uses: actions/checkout@v3
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: '14'
        - run: npm install
        - name: Create SBOM with CycloneDX
          id: sbom_output
          uses: CycloneDX/gh-node-module-generatebom@master
        - name: Create SBOM with CycloneDX
          id: step_one
          run: |
           echo "FOO=$(git status)" >> $GITHUB_ENV
        - name: REST API with curl
          run: |
            curl \
            -X POST \
            https://dummyjson.com/products/add \
            -d {"client_payload":{title:"pencil"}}
        - name: PRINT job1 SBOM
          run: echo "${{ env.FOO }}"
