name: Build javascript project
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.sbom.outputs.test }}
    name: Install and build javascript
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - name: Create SBOM with CycloneDX
        id: sbom
        uses: CycloneDX/gh-node-module-generatebom@master 
        with:
            output: './test.app.bom.xml'
      - name: save sbom
        id: step_one
        run: | 
           echo "test<<EOF" >> $GITHUB_OUTPUT
           echo "$(cat './test.app.bom.xml')" >> $GITHUB_OUTPUT
           echo "EOF" >> $GITHUB_OUTPUT 
           echo "SBOM: $(cat './test.app.bom.xml')"     
  job2:
   runs-on: ubuntu-latest
   needs: job1
   steps:
    - run: echo ${{needs.job1.outputs.output1}}
       
        
