name: Build node.js project
on: push
jobs:
  job1:
      runs-on: ubuntu-latest
      name: SBOM generator
      steps:
        - uses: actions/checkout@v3
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: '14'
        - run: npm install
        - name: Create SBOM with CycloneDX 
          id: sbom_output
          uses: CycloneDX/gh-node-module-generatebom@master
          with: 
           output: './test.app.bom.xml'
        - name: save_sbom
          id: step_one
          run: |
           echo "sbom=${{job1.sbom_output.output}}" >> $GITHUB_ENV
        - name: Use the value
          id: step_two
          run: |
            echo "${{ env.sbom }}" # This will output 'SBOM'
