name: Build node.js project
on: push
jobs:
  job1:
      runs-on: ubuntu-latest
      name: SBOM generator 
      steps:
        - uses: actions/checkout@v3
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: '14'
        - run: npm install
        - name: Create SBOM with CycloneDX 
          id: sbom_generator
          uses: CycloneDX/gh-node-module-generatebom@master
          with: 
           path: './node_project/'
           output: './bom_directory/test.app.bom.xml'
