name: Build sbom projects
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.save_sbom.outputs.test }}
    name: Install all dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - name: Create SBOM with CycloneDX
        id: sbom
        uses: CycloneDX/gh-node-module-generatebom@master 
        with:
            output: './test.app.bom.json'
      - name: save sbom
        id: save_sbom
        run: | 
          echo "test<<EOF" >> $GITHUB_OUTPUT
          echo "$(cat './test.app.bom.json')" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
         
  
  job2:  
     runs-on: ubuntu-latest
     name: Call api
     needs: job1
     steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
         curl --request POST \
         --url "https://api.github.com/repos/octocat/Spoon-Knife/issues" \
         --header "Accept: application/vnd.github+json" \
         --data '${{needs.job1.outputs.output1}}'
